import 'package:hive/hive.dart';

part 'app_settings.g.dart'; // Will be generated by build_runner

@HiveType(
    typeId:
        2) // Using typeId 2, assuming ComparisonSession is 1 (or other unused ID)
class AppSettings extends HiveObject {
  @HiveField(0, defaultValue: 'Auto')
  String defaultSourceFormat;

  @HiveField(1, defaultValue: 'Auto')
  String defaultTargetFormat;

  @HiveField(2, defaultValue: ['^//.*', '^#.*'])
  List<String> ignorePatterns;

  @HiveField(3, defaultValue: true)
  bool ignoreCase;

  @HiveField(4, defaultValue: false)
  bool ignoreWhitespace;

  @HiveField(5, defaultValue: 'English (US)')
  String appLanguage;

  @HiveField(6, defaultValue: 'Basic Comparison')
  String defaultViewOnStartup;

  @HiveField(7, defaultValue: true)
  bool autoCheckForUpdates;

  @HiveField(8, defaultValue: 'System')
  String appThemeMode;

  @HiveField(9, defaultValue: 0xFF7B61FF)
  int accentColorValue;

  @HiveField(10, defaultValue: 0xFF4CAF50)
  int diffAddedColor;

  @HiveField(11, defaultValue: 0xFFF44336)
  int diffRemovedColor;

  @HiveField(12, defaultValue: 0xFFFFC107)
  int diffModifiedColor;

  @HiveField(37, defaultValue: 14.0)
  double diffFontSize;

  @HiveField(13, defaultValue: 'UTF-8')
  String defaultSourceEncoding;

  @HiveField(14, defaultValue: 'UTF-8')
  String defaultTargetEncoding;

  @HiveField(15, defaultValue: true)
  bool autoDetectEncoding;

  @HiveField(16, defaultValue: ',')
  String csvDelimiter;

  @HiveField(17, defaultValue: true)
  bool handleByteOrderMark;

  @HiveField(18, defaultValue: true)
  bool autoReloadOnChange;

  @HiveField(19, defaultValue: '')
  String defaultExportDirectory;

  // AI Services Settings
  @HiveField(20, defaultValue: 'Google Translate')
  String aiTranslationService;

  @HiveField(21, defaultValue: '')
  String googleTranslateApiKey;

  @HiveField(22, defaultValue: '')
  String deeplApiKey;

  @HiveField(23, defaultValue: false)
  bool enableAiTranslation;

  @HiveField(24, defaultValue: 0.8)
  double translationConfidenceThreshold;

  // LLM Translation Settings
  @HiveField(30, defaultValue: '')
  String geminiApiKey;

  @HiveField(31, defaultValue: '')
  String openaiApiKey;

  @HiveField(32, defaultValue: '')
  String defaultAiModel;

  @HiveField(33, defaultValue: '')
  String systemTranslationContext;

  @HiveField(34, defaultValue: 2)
  int contextStringsCount;

  @HiveField(35, defaultValue: false)
  bool includeContextStrings;

  @HiveField(58, defaultValue: true)
  bool enableTranslationMemory;

  @HiveField(59, defaultValue: true)
  bool enableFuzzyFill;

  @HiveField(60, defaultValue: 0.6)
  double fuzzyFillMinScore;

  @HiveField(61, defaultValue: false)
  bool fuzzyFillAutoApply;

  @HiveField(62, defaultValue: true)
  bool fuzzyFillOnlyEmptyTargets;

  @HiveField(63, defaultValue: 3)
  int fuzzyFillMatchLimit;

  @HiveField(64, defaultValue: false)
  bool fuzzyFillExactMatchesOnly;

  // Version Control Settings
  @HiveField(25, defaultValue: '')
  String defaultGitRepositoryPath;

  @HiveField(26, defaultValue: false)
  bool autoCommitOnSave;

  @HiveField(27, defaultValue: '')
  String gitUserName;

  @HiveField(28, defaultValue: '')
  String gitUserEmail;

  @HiveField(29, defaultValue: false)
  bool enableGitIntegration;

  @HiveField(65, defaultValue: 'main')
  String defaultBranch;

  @HiveField(66, defaultValue: 'origin')
  String defaultRemote;

  @HiveField(67, defaultValue: 'Update localization: {files}')
  String commitMessageTemplate;

  @HiveField(68, defaultValue: '')
  String sshKeyPath;

  @HiveField(36, defaultValue: true)
  bool showIdenticalEntries;

  // Startup Options
  @HiveField(38, defaultValue: false)
  bool startMinimizedToTray;

  @HiveField(39, defaultValue: false)
  bool openLastProjectOnStartup;

  @HiveField(40, defaultValue: false)
  bool rememberWindowPosition;

  @HiveField(41)
  double? lastWindowX;

  @HiveField(42)
  double? lastWindowY;

  @HiveField(43)
  double? lastWindowWidth;

  @HiveField(44)
  double? lastWindowHeight;

  // Comparison Engine - Similarity Threshold
  @HiveField(45, defaultValue: 0.85)
  double similarityThreshold;

  // AI Model Parameters
  @HiveField(56, defaultValue: 0.7)
  double aiTemperature;

  @HiveField(57, defaultValue: 2048)
  int maxTokens;

  // Comparison Engine - Comparison Mode
  @HiveField(46, defaultValue: 'Key-based')
  String comparisonMode;

  // Windows Integration Settings
  @HiveField(47, defaultValue: false)
  bool useMicaEffect;

  // Diff Font Family
  @HiveField(48, defaultValue: 'System Default')
  String diffFontFamily;

  // Identical Entry Color
  @HiveField(49, defaultValue: 0xFF9E9E9E)
  int diffIdenticalColor;

  // Export Settings
  @HiveField(50, defaultValue: 'CSV')
  String defaultExportFormat;

  @HiveField(51, defaultValue: true)
  bool includeUtf8Bom;

  @HiveField(52, defaultValue: true)
  bool openFolderAfterExport;

  // Backup Settings
  @HiveField(53, defaultValue: true)
  bool autoBackup;

  @HiveField(54, defaultValue: '')
  String backupDirectory;

  @HiveField(55, defaultValue: 5)
  int backupsToKeep;

  AppSettings({
    required this.defaultSourceFormat,
    required this.defaultTargetFormat,
    required this.ignorePatterns,
    required this.ignoreCase,
    required this.ignoreWhitespace,
    required this.appLanguage,
    required this.defaultViewOnStartup,
    required this.autoCheckForUpdates,
    required this.appThemeMode,
    required this.accentColorValue,
    required this.diffAddedColor,
    required this.diffRemovedColor,
    required this.diffModifiedColor,
    required this.diffFontSize,
    required this.defaultSourceEncoding,
    required this.defaultTargetEncoding,
    required this.autoDetectEncoding,
    required this.csvDelimiter,
    required this.handleByteOrderMark,
    required this.autoReloadOnChange,
    required this.defaultExportDirectory,
    required this.aiTranslationService,
    required this.googleTranslateApiKey,
    required this.deeplApiKey,
    required this.enableAiTranslation,
    required this.translationConfidenceThreshold,
    required this.geminiApiKey,
    required this.openaiApiKey,
    required this.defaultAiModel,
    required this.systemTranslationContext,
    required this.contextStringsCount,
    required this.includeContextStrings,
    required this.enableTranslationMemory,
    required this.enableFuzzyFill,
    required this.fuzzyFillMinScore,
    required this.fuzzyFillAutoApply,
    required this.fuzzyFillOnlyEmptyTargets,
    required this.fuzzyFillMatchLimit,
    required this.fuzzyFillExactMatchesOnly,
    required this.defaultGitRepositoryPath,
    required this.autoCommitOnSave,
    required this.gitUserName,
    required this.gitUserEmail,
    required this.enableGitIntegration,
    required this.defaultBranch,
    required this.defaultRemote,
    required this.commitMessageTemplate,
    required this.sshKeyPath,
    required this.showIdenticalEntries,
    required this.startMinimizedToTray,
    required this.openLastProjectOnStartup,
    required this.rememberWindowPosition,
    this.lastWindowX,
    this.lastWindowY,
    this.lastWindowWidth,
    this.lastWindowHeight,
    required this.similarityThreshold,
    required this.aiTemperature,
    required this.maxTokens,
    required this.comparisonMode,
    required this.useMicaEffect,
    required this.diffFontFamily,
    required this.diffIdenticalColor,
    required this.defaultExportFormat,
    required this.includeUtf8Bom,
    required this.openFolderAfterExport,
    required this.autoBackup,
    required this.backupDirectory,
    required this.backupsToKeep,
  });

  // Default settings
  factory AppSettings.defaultSettings() {
    return AppSettings(
      defaultSourceFormat: 'Auto',
      defaultTargetFormat: 'Auto',
      ignorePatterns: ['^//.*', '^#.*'],
      ignoreCase: true,
      ignoreWhitespace: false,
      appLanguage: 'English (US)', // Default for new field
      defaultViewOnStartup: 'Basic Comparison', // Default for new field
      autoCheckForUpdates: true, // Default for new field
      appThemeMode: 'System', // Default for new field
      accentColorValue:
          0xFF7B61FF, // Default for new field (Color(0xFF7B61FF).value)
      diffAddedColor: 0xFF4CAF50, // Material Green
      diffRemovedColor: 0xFFF44336, // Material Red
      diffModifiedColor: 0xFFFFC107, // Material Amber
      diffFontSize: 14.0, // Default font size
      defaultSourceEncoding: 'UTF-8',
      defaultTargetEncoding: 'UTF-8',
      autoDetectEncoding: true,
      csvDelimiter: ',',
      handleByteOrderMark: true,
      autoReloadOnChange: true,
      defaultExportDirectory: '',
      aiTranslationService: 'Google Translate',
      googleTranslateApiKey: '',
      deeplApiKey: '',
      enableAiTranslation: false,
      translationConfidenceThreshold: 0.8,
      geminiApiKey: '',
      openaiApiKey: '',
      defaultAiModel: '',
      systemTranslationContext: '',
      contextStringsCount: 2,
      includeContextStrings: false,
      enableTranslationMemory: true,
      enableFuzzyFill: true,
      fuzzyFillMinScore: 0.6,
      fuzzyFillAutoApply: false,
      fuzzyFillOnlyEmptyTargets: true,
      fuzzyFillMatchLimit: 3,
      fuzzyFillExactMatchesOnly: false,
      defaultGitRepositoryPath: '',
      autoCommitOnSave: false,
      gitUserName: '',
      gitUserEmail: '',
      enableGitIntegration: false,
      defaultBranch: 'main',
      defaultRemote: 'origin',
      commitMessageTemplate: 'Update localization: {files}',
      sshKeyPath: '',
      showIdenticalEntries: true,
      startMinimizedToTray: false,
      openLastProjectOnStartup: false,
      rememberWindowPosition: false,
      lastWindowX: null,
      lastWindowY: null,
      lastWindowWidth: null,
      lastWindowHeight: null,
      similarityThreshold: 0.85,
      aiTemperature: 0.7,
      maxTokens: 2048,
      comparisonMode: 'Key-based',
      useMicaEffect: false,
      diffFontFamily: 'System Default',
      diffIdenticalColor: 0xFF9E9E9E, // Subtle gray
      defaultExportFormat: 'CSV',
      includeUtf8Bom: true,
      openFolderAfterExport: true,
      autoBackup: true,
      backupDirectory: '',
      backupsToKeep: 5,
    );
  }

  // From JSON
  factory AppSettings.fromJson(Map<String, dynamic> json) {
    return AppSettings(
      defaultSourceFormat: json['defaultSourceFormat'] as String,
      defaultTargetFormat: json['defaultTargetFormat'] as String,
      ignorePatterns: List<String>.from(json['ignorePatterns']),
      ignoreCase: json['ignoreCase'] as bool,
      ignoreWhitespace: json['ignoreWhitespace'] as bool,
      appLanguage: json['appLanguage'] as String,
      defaultViewOnStartup: json['defaultViewOnStartup'] as String,
      autoCheckForUpdates: json['autoCheckForUpdates'] as bool,
      appThemeMode: json['appThemeMode'] as String,
      accentColorValue: json['accentColorValue'] as int,
      diffAddedColor: json['diffAddedColor'] as int,
      diffRemovedColor: json['diffRemovedColor'] as int,
      diffModifiedColor: json['diffModifiedColor'] as int,
      diffFontSize: (json['diffFontSize'] as num?)?.toDouble() ?? 14.0,
      defaultSourceEncoding: json['defaultSourceEncoding'] as String,
      defaultTargetEncoding: json['defaultTargetEncoding'] as String,
      autoDetectEncoding: json['autoDetectEncoding'] as bool,
      csvDelimiter: json['csvDelimiter'] as String,
      handleByteOrderMark: json['handleByteOrderMark'] as bool,
      autoReloadOnChange: json['autoReloadOnChange'] as bool,
      defaultExportDirectory: json['defaultExportDirectory'] as String,
      aiTranslationService: json['aiTranslationService'] as String,
      googleTranslateApiKey: json['googleTranslateApiKey'] as String,
      deeplApiKey: json['deeplApiKey'] as String,
      enableAiTranslation: json['enableAiTranslation'] as bool,
      translationConfidenceThreshold:
          json['translationConfidenceThreshold'] as double,
      geminiApiKey: json['geminiApiKey'] as String? ?? '',
      openaiApiKey: json['openaiApiKey'] as String? ?? '',
      defaultAiModel: json['defaultAiModel'] as String? ?? '',
      systemTranslationContext:
          json['systemTranslationContext'] as String? ?? '',
      contextStringsCount: json['contextStringsCount'] as int? ?? 2,
      includeContextStrings: json['includeContextStrings'] as bool? ?? false,
      enableTranslationMemory: json['enableTranslationMemory'] as bool? ?? true,
      enableFuzzyFill: json['enableFuzzyFill'] as bool? ?? true,
      fuzzyFillMinScore: (json['fuzzyFillMinScore'] as num?)?.toDouble() ?? 0.6,
      fuzzyFillAutoApply: json['fuzzyFillAutoApply'] as bool? ?? false,
      fuzzyFillOnlyEmptyTargets:
          json['fuzzyFillOnlyEmptyTargets'] as bool? ?? true,
      fuzzyFillMatchLimit: json['fuzzyFillMatchLimit'] as int? ?? 3,
      fuzzyFillExactMatchesOnly:
          json['fuzzyFillExactMatchesOnly'] as bool? ?? false,
      defaultGitRepositoryPath: json['defaultGitRepositoryPath'] as String,
      autoCommitOnSave: json['autoCommitOnSave'] as bool,
      gitUserName: json['gitUserName'] as String,
      gitUserEmail: json['gitUserEmail'] as String,
      enableGitIntegration: json['enableGitIntegration'] as bool,
      defaultBranch: json['defaultBranch'] as String? ?? 'main',
      defaultRemote: json['defaultRemote'] as String? ?? 'origin',
      commitMessageTemplate: json['commitMessageTemplate'] as String? ?? 'Update localization: {files}',
      sshKeyPath: json['sshKeyPath'] as String? ?? '',
      showIdenticalEntries: json['showIdenticalEntries'] as bool? ?? true,
      startMinimizedToTray: json['startMinimizedToTray'] as bool? ?? false,
      openLastProjectOnStartup:
          json['openLastProjectOnStartup'] as bool? ?? false,
      rememberWindowPosition: json['rememberWindowPosition'] as bool? ?? false,
      lastWindowX: (json['lastWindowX'] as num?)?.toDouble(),
      lastWindowY: (json['lastWindowY'] as num?)?.toDouble(),
      lastWindowWidth: (json['lastWindowWidth'] as num?)?.toDouble(),
      lastWindowHeight: (json['lastWindowHeight'] as num?)?.toDouble(),
      similarityThreshold:
          (json['similarityThreshold'] as num?)?.toDouble() ?? 0.85,
      aiTemperature: (json['aiTemperature'] as num?)?.toDouble() ?? 0.7,
      maxTokens: json['maxTokens'] as int? ?? 2048,
      comparisonMode: json['comparisonMode'] as String? ?? 'Key-based',
      useMicaEffect: json['useMicaEffect'] as bool? ?? false,
      diffFontFamily: json['diffFontFamily'] as String? ?? 'System Default',
      diffIdenticalColor: json['diffIdenticalColor'] as int? ?? 0xFF9E9E9E,
      defaultExportFormat: json['defaultExportFormat'] as String? ?? 'CSV',
      includeUtf8Bom: json['includeUtf8Bom'] as bool? ?? true,
      openFolderAfterExport: json['openFolderAfterExport'] as bool? ?? true,
      autoBackup: json['autoBackup'] as bool? ?? true,
      backupDirectory: json['backupDirectory'] as String? ?? '',
      backupsToKeep: json['backupsToKeep'] as int? ?? 5,
    );
  }

  // To JSON
  Map<String, dynamic> toJson() {
    return {
      'defaultSourceFormat': defaultSourceFormat,
      'defaultTargetFormat': defaultTargetFormat,
      'ignorePatterns': ignorePatterns,
      'ignoreCase': ignoreCase,
      'ignoreWhitespace': ignoreWhitespace,
      'appLanguage': appLanguage,
      'defaultViewOnStartup': defaultViewOnStartup,
      'autoCheckForUpdates': autoCheckForUpdates,
      'appThemeMode': appThemeMode,
      'accentColorValue': accentColorValue,
      'diffAddedColor': diffAddedColor,
      'diffRemovedColor': diffRemovedColor,
      'diffModifiedColor': diffModifiedColor,
      'diffFontSize': diffFontSize,
      'defaultSourceEncoding': defaultSourceEncoding,
      'defaultTargetEncoding': defaultTargetEncoding,
      'autoDetectEncoding': autoDetectEncoding,
      'csvDelimiter': csvDelimiter,
      'handleByteOrderMark': handleByteOrderMark,
      'autoReloadOnChange': autoReloadOnChange,
      'defaultExportDirectory': defaultExportDirectory,
      'aiTranslationService': aiTranslationService,
      'googleTranslateApiKey': googleTranslateApiKey,
      'deeplApiKey': deeplApiKey,
      'enableAiTranslation': enableAiTranslation,
      'translationConfidenceThreshold': translationConfidenceThreshold,
      'geminiApiKey': geminiApiKey,
      'openaiApiKey': openaiApiKey,
      'defaultAiModel': defaultAiModel,
      'systemTranslationContext': systemTranslationContext,
      'contextStringsCount': contextStringsCount,
      'includeContextStrings': includeContextStrings,
      'enableTranslationMemory': enableTranslationMemory,
      'enableFuzzyFill': enableFuzzyFill,
      'fuzzyFillMinScore': fuzzyFillMinScore,
      'fuzzyFillAutoApply': fuzzyFillAutoApply,
      'fuzzyFillOnlyEmptyTargets': fuzzyFillOnlyEmptyTargets,
      'fuzzyFillMatchLimit': fuzzyFillMatchLimit,
      'fuzzyFillExactMatchesOnly': fuzzyFillExactMatchesOnly,
      'defaultGitRepositoryPath': defaultGitRepositoryPath,
      'autoCommitOnSave': autoCommitOnSave,
      'gitUserName': gitUserName,
      'gitUserEmail': gitUserEmail,
      'enableGitIntegration': enableGitIntegration,
      'defaultBranch': defaultBranch,
      'defaultRemote': defaultRemote,
      'commitMessageTemplate': commitMessageTemplate,
      'sshKeyPath': sshKeyPath,
      'showIdenticalEntries': showIdenticalEntries,
      'startMinimizedToTray': startMinimizedToTray,
      'openLastProjectOnStartup': openLastProjectOnStartup,
      'rememberWindowPosition': rememberWindowPosition,
      'lastWindowX': lastWindowX,
      'lastWindowY': lastWindowY,
      'lastWindowWidth': lastWindowWidth,
      'lastWindowHeight': lastWindowHeight,
      'similarityThreshold': similarityThreshold,
      'comparisonMode': comparisonMode,
      'useMicaEffect': useMicaEffect,
      'diffFontFamily': diffFontFamily,
      'diffIdenticalColor': diffIdenticalColor,
      'defaultExportFormat': defaultExportFormat,
      'includeUtf8Bom': includeUtf8Bom,
      'openFolderAfterExport': openFolderAfterExport,
      'autoBackup': autoBackup,
      'backupDirectory': backupDirectory,
      'backupsToKeep': backupsToKeep,
      'aiTemperature': aiTemperature,
      'maxTokens': maxTokens,
    };
  }

  AppSettings copyWith({
    String? defaultSourceFormat,
    String? defaultTargetFormat,
    List<String>? ignorePatterns,
    bool? ignoreCase,
    bool? ignoreWhitespace,
    String? appLanguage,
    String? defaultViewOnStartup,
    bool? autoCheckForUpdates,
    String? appThemeMode,
    int? accentColorValue,
    int? diffAddedColor,
    int? diffRemovedColor,
    int? diffModifiedColor,
    double? diffFontSize,
    String? defaultSourceEncoding,
    String? defaultTargetEncoding,
    bool? autoDetectEncoding,
    String? csvDelimiter,
    bool? handleByteOrderMark,
    bool? autoReloadOnChange,
    String? defaultExportDirectory,
    String? aiTranslationService,
    String? googleTranslateApiKey,
    String? deeplApiKey,
    bool? enableAiTranslation,
    double? translationConfidenceThreshold,
    String? geminiApiKey,
    String? openaiApiKey,
    String? defaultAiModel,
    String? systemTranslationContext,
    int? contextStringsCount,
    bool? includeContextStrings,
    bool? enableTranslationMemory,
    bool? enableFuzzyFill,
    double? fuzzyFillMinScore,
    bool? fuzzyFillAutoApply,
    bool? fuzzyFillOnlyEmptyTargets,
    int? fuzzyFillMatchLimit,
    bool? fuzzyFillExactMatchesOnly,
    String? defaultGitRepositoryPath,
    bool? autoCommitOnSave,
    String? gitUserName,
    String? gitUserEmail,
    bool? enableGitIntegration,
    String? defaultBranch,
    String? defaultRemote,
    String? commitMessageTemplate,
    String? sshKeyPath,
    bool? showIdenticalEntries,
    bool? startMinimizedToTray,
    bool? openLastProjectOnStartup,
    bool? rememberWindowPosition,
    double? lastWindowX,
    double? lastWindowY,
    double? lastWindowWidth,
    double? lastWindowHeight,
    double? similarityThreshold,
    double? aiTemperature,
    int? maxTokens,
    String? comparisonMode,
    bool? useMicaEffect,
    String? diffFontFamily,
    int? diffIdenticalColor,
    String? defaultExportFormat,
    bool? includeUtf8Bom,
    bool? openFolderAfterExport,
    bool? autoBackup,
    String? backupDirectory,
    int? backupsToKeep,
  }) {
    return AppSettings(
      defaultSourceFormat: defaultSourceFormat ?? this.defaultSourceFormat,
      defaultTargetFormat: defaultTargetFormat ?? this.defaultTargetFormat,
      ignorePatterns: ignorePatterns ?? this.ignorePatterns,
      ignoreCase: ignoreCase ?? this.ignoreCase,
      ignoreWhitespace: ignoreWhitespace ?? this.ignoreWhitespace,
      appLanguage: appLanguage ?? this.appLanguage,
      defaultViewOnStartup: defaultViewOnStartup ?? this.defaultViewOnStartup,
      autoCheckForUpdates: autoCheckForUpdates ?? this.autoCheckForUpdates,
      appThemeMode: appThemeMode ?? this.appThemeMode,
      accentColorValue: accentColorValue ?? this.accentColorValue,
      diffAddedColor: diffAddedColor ?? this.diffAddedColor,
      diffRemovedColor: diffRemovedColor ?? this.diffRemovedColor,
      diffModifiedColor: diffModifiedColor ?? this.diffModifiedColor,
      diffFontSize: diffFontSize ?? this.diffFontSize,
      defaultSourceEncoding:
          defaultSourceEncoding ?? this.defaultSourceEncoding,
      defaultTargetEncoding:
          defaultTargetEncoding ?? this.defaultTargetEncoding,
      autoDetectEncoding: autoDetectEncoding ?? this.autoDetectEncoding,
      csvDelimiter: csvDelimiter ?? this.csvDelimiter,
      handleByteOrderMark: handleByteOrderMark ?? this.handleByteOrderMark,
      autoReloadOnChange: autoReloadOnChange ?? this.autoReloadOnChange,
      defaultExportDirectory:
          defaultExportDirectory ?? this.defaultExportDirectory,
      aiTranslationService: aiTranslationService ?? this.aiTranslationService,
      googleTranslateApiKey:
          googleTranslateApiKey ?? this.googleTranslateApiKey,
      deeplApiKey: deeplApiKey ?? this.deeplApiKey,
      enableAiTranslation: enableAiTranslation ?? this.enableAiTranslation,
      translationConfidenceThreshold:
          translationConfidenceThreshold ?? this.translationConfidenceThreshold,
      geminiApiKey: geminiApiKey ?? this.geminiApiKey,
      openaiApiKey: openaiApiKey ?? this.openaiApiKey,
      defaultAiModel: defaultAiModel ?? this.defaultAiModel,
      systemTranslationContext:
          systemTranslationContext ?? this.systemTranslationContext,
      contextStringsCount: contextStringsCount ?? this.contextStringsCount,
      includeContextStrings:
          includeContextStrings ?? this.includeContextStrings,
      enableTranslationMemory:
          enableTranslationMemory ?? this.enableTranslationMemory,
      enableFuzzyFill: enableFuzzyFill ?? this.enableFuzzyFill,
      fuzzyFillMinScore: fuzzyFillMinScore ?? this.fuzzyFillMinScore,
      fuzzyFillAutoApply: fuzzyFillAutoApply ?? this.fuzzyFillAutoApply,
      fuzzyFillOnlyEmptyTargets:
          fuzzyFillOnlyEmptyTargets ?? this.fuzzyFillOnlyEmptyTargets,
      fuzzyFillMatchLimit: fuzzyFillMatchLimit ?? this.fuzzyFillMatchLimit,
      fuzzyFillExactMatchesOnly:
          fuzzyFillExactMatchesOnly ?? this.fuzzyFillExactMatchesOnly,
      defaultGitRepositoryPath:
          defaultGitRepositoryPath ?? this.defaultGitRepositoryPath,
      autoCommitOnSave: autoCommitOnSave ?? this.autoCommitOnSave,
      gitUserName: gitUserName ?? this.gitUserName,
      gitUserEmail: gitUserEmail ?? this.gitUserEmail,
      enableGitIntegration: enableGitIntegration ?? this.enableGitIntegration,
      defaultBranch: defaultBranch ?? this.defaultBranch,
      defaultRemote: defaultRemote ?? this.defaultRemote,
      commitMessageTemplate: commitMessageTemplate ?? this.commitMessageTemplate,
      sshKeyPath: sshKeyPath ?? this.sshKeyPath,
      showIdenticalEntries: showIdenticalEntries ?? this.showIdenticalEntries,
      startMinimizedToTray: startMinimizedToTray ?? this.startMinimizedToTray,
      openLastProjectOnStartup:
          openLastProjectOnStartup ?? this.openLastProjectOnStartup,
      rememberWindowPosition:
          rememberWindowPosition ?? this.rememberWindowPosition,
      lastWindowX: lastWindowX ?? this.lastWindowX,
      lastWindowY: lastWindowY ?? this.lastWindowY,
      lastWindowWidth: lastWindowWidth ?? this.lastWindowWidth,
      lastWindowHeight: lastWindowHeight ?? this.lastWindowHeight,
      similarityThreshold: similarityThreshold ?? this.similarityThreshold,
      aiTemperature: aiTemperature ?? this.aiTemperature,
      maxTokens: maxTokens ?? this.maxTokens,
      comparisonMode: comparisonMode ?? this.comparisonMode,
      useMicaEffect: useMicaEffect ?? this.useMicaEffect,
      diffFontFamily: diffFontFamily ?? this.diffFontFamily,
      diffIdenticalColor: diffIdenticalColor ?? this.diffIdenticalColor,
      defaultExportFormat: defaultExportFormat ?? this.defaultExportFormat,
      includeUtf8Bom: includeUtf8Bom ?? this.includeUtf8Bom,
      openFolderAfterExport:
          openFolderAfterExport ?? this.openFolderAfterExport,
      autoBackup: autoBackup ?? this.autoBackup,
      backupDirectory: backupDirectory ?? this.backupDirectory,
      backupsToKeep: backupsToKeep ?? this.backupsToKeep,
    );
  }
}
