import 'package:hive/hive.dart';

part 'app_settings.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 2) // Using typeId 2, assuming ComparisonSession is 1 (or other unused ID)
class AppSettings extends HiveObject {
  @HiveField(0, defaultValue: 'json')
  String defaultSourceFormat;

  @HiveField(1, defaultValue: 'json')
  String defaultTargetFormat;

  @HiveField(2, defaultValue: ['^//.*', '^#.*'])
  List<String> ignorePatterns;

  @HiveField(3, defaultValue: true)
  bool ignoreCase;

  @HiveField(4, defaultValue: false)
  bool ignoreWhitespace;

  @HiveField(5, defaultValue: 'English (US)')
  String appLanguage;

  @HiveField(6, defaultValue: 'Basic Comparison')
  String defaultViewOnStartup;

  @HiveField(7, defaultValue: true)
  bool autoCheckForUpdates;

  @HiveField(8, defaultValue: 'System')
  String appThemeMode;

  @HiveField(9, defaultValue: 0xFF7B61FF)
  int accentColorValue;

  @HiveField(10, defaultValue: 0xFF4CAF50)
  int diffAddedColor;

  @HiveField(11, defaultValue: 0xFFF44336)
  int diffRemovedColor;

  @HiveField(12, defaultValue: 0xFFFFC107)
  int diffModifiedColor;

  @HiveField(37, defaultValue: 14.0)
  double diffFontSize;

  @HiveField(13, defaultValue: 'UTF-8')
  String defaultSourceEncoding;

  @HiveField(14, defaultValue: 'UTF-8')
  String defaultTargetEncoding;

  @HiveField(15, defaultValue: true)
  bool autoDetectEncoding;

  @HiveField(16, defaultValue: ',')
  String csvDelimiter;

  @HiveField(17, defaultValue: true)
  bool handleByteOrderMark;

  @HiveField(18, defaultValue: true)
  bool autoReloadOnChange;

  @HiveField(19, defaultValue: '')
  String defaultExportDirectory;

  // AI Services Settings
  @HiveField(20, defaultValue: 'Google Translate')
  String aiTranslationService;

  @HiveField(21, defaultValue: '')
  String googleTranslateApiKey;

  @HiveField(22, defaultValue: '')
  String deeplApiKey;

  @HiveField(23, defaultValue: false)
  bool enableAiTranslation;

  @HiveField(24, defaultValue: 0.8)
  double translationConfidenceThreshold;

  // LLM Translation Settings
  @HiveField(30, defaultValue: '')
  String geminiApiKey;

  @HiveField(31, defaultValue: '')
  String openaiApiKey;

  @HiveField(32, defaultValue: '')
  String defaultAiModel;

  @HiveField(33, defaultValue: '')
  String systemTranslationContext;

  @HiveField(34, defaultValue: 2)
  int contextStringsCount;

  @HiveField(35, defaultValue: false)
  bool includeContextStrings;

  // Version Control Settings
  @HiveField(25, defaultValue: '')
  String defaultGitRepositoryPath;

  @HiveField(26, defaultValue: false)
  bool autoCommitOnSave;

  @HiveField(27, defaultValue: '')
  String gitUserName;

  @HiveField(28, defaultValue: '')
  String gitUserEmail;

  @HiveField(29, defaultValue: false)
  bool enableGitIntegration;

  @HiveField(36, defaultValue: true)
  bool showIdenticalEntries;

  AppSettings({
    required this.defaultSourceFormat,
    required this.defaultTargetFormat,
    required this.ignorePatterns,
    required this.ignoreCase,
    required this.ignoreWhitespace,
    required this.appLanguage,
    required this.defaultViewOnStartup,
    required this.autoCheckForUpdates,
    required this.appThemeMode,
    required this.accentColorValue,
    required this.diffAddedColor,
    required this.diffRemovedColor,
    required this.diffModifiedColor,
    required this.diffFontSize,
    required this.defaultSourceEncoding,
    required this.defaultTargetEncoding,
    required this.autoDetectEncoding,
    required this.csvDelimiter,
    required this.handleByteOrderMark,
    required this.autoReloadOnChange,
    required this.defaultExportDirectory,
    required this.aiTranslationService,
    required this.googleTranslateApiKey,
    required this.deeplApiKey,
    required this.enableAiTranslation,
    required this.translationConfidenceThreshold,
    required this.geminiApiKey,
    required this.openaiApiKey,
    required this.defaultAiModel,
    required this.systemTranslationContext,
    required this.contextStringsCount,
    required this.includeContextStrings,
    required this.defaultGitRepositoryPath,
    required this.autoCommitOnSave,
    required this.gitUserName,
    required this.gitUserEmail,
    required this.enableGitIntegration,
    required this.showIdenticalEntries,
  });

  // Default settings
  factory AppSettings.defaultSettings() {
    return AppSettings(
      defaultSourceFormat: 'json',
      defaultTargetFormat: 'json',
      ignorePatterns: ['^//.*', '^#.*'],
      ignoreCase: true,
      ignoreWhitespace: false,
      appLanguage: 'English (US)', // Default for new field
      defaultViewOnStartup: 'Basic Comparison', // Default for new field
      autoCheckForUpdates: true, // Default for new field
      appThemeMode: 'System', // Default for new field
      accentColorValue: 0xFF7B61FF, // Default for new field (Color(0xFF7B61FF).value)
      diffAddedColor: 0xFF4CAF50, // Material Green
      diffRemovedColor: 0xFFF44336, // Material Red
      diffModifiedColor: 0xFFFFC107, // Material Amber
      diffFontSize: 14.0, // Default font size
      defaultSourceEncoding: 'UTF-8',
      defaultTargetEncoding: 'UTF-8',
      autoDetectEncoding: true,
      csvDelimiter: ',',
      handleByteOrderMark: true,
      autoReloadOnChange: true,
      defaultExportDirectory: '',
      aiTranslationService: 'Google Translate',
      googleTranslateApiKey: '',
      deeplApiKey: '',
      enableAiTranslation: false,
      translationConfidenceThreshold: 0.8,
      geminiApiKey: '',
      openaiApiKey: '',
      defaultAiModel: '',
      systemTranslationContext: '',
      contextStringsCount: 2,
      includeContextStrings: false,
      defaultGitRepositoryPath: '',
      autoCommitOnSave: false,
      gitUserName: '',
      gitUserEmail: '',
      enableGitIntegration: false,
      showIdenticalEntries: true,
    );
  }

  // From JSON
  factory AppSettings.fromJson(Map<String, dynamic> json) {
    return AppSettings(
      defaultSourceFormat: json['defaultSourceFormat'] as String,
      defaultTargetFormat: json['defaultTargetFormat'] as String,
      ignorePatterns: List<String>.from(json['ignorePatterns']),
      ignoreCase: json['ignoreCase'] as bool,
      ignoreWhitespace: json['ignoreWhitespace'] as bool,
      appLanguage: json['appLanguage'] as String,
      defaultViewOnStartup: json['defaultViewOnStartup'] as String,
      autoCheckForUpdates: json['autoCheckForUpdates'] as bool,
      appThemeMode: json['appThemeMode'] as String,
      accentColorValue: json['accentColorValue'] as int,
      diffAddedColor: json['diffAddedColor'] as int,
      diffRemovedColor: json['diffRemovedColor'] as int,
      diffModifiedColor: json['diffModifiedColor'] as int,
      diffFontSize: (json['diffFontSize'] as num?)?.toDouble() ?? 14.0,
      defaultSourceEncoding: json['defaultSourceEncoding'] as String,
      defaultTargetEncoding: json['defaultTargetEncoding'] as String,
      autoDetectEncoding: json['autoDetectEncoding'] as bool,
      csvDelimiter: json['csvDelimiter'] as String,
      handleByteOrderMark: json['handleByteOrderMark'] as bool,
      autoReloadOnChange: json['autoReloadOnChange'] as bool,
      defaultExportDirectory: json['defaultExportDirectory'] as String,
      aiTranslationService: json['aiTranslationService'] as String,
      googleTranslateApiKey: json['googleTranslateApiKey'] as String,
      deeplApiKey: json['deeplApiKey'] as String,
      enableAiTranslation: json['enableAiTranslation'] as bool,
      translationConfidenceThreshold: json['translationConfidenceThreshold'] as double,
      geminiApiKey: json['geminiApiKey'] as String? ?? '',
      openaiApiKey: json['openaiApiKey'] as String? ?? '',
      defaultAiModel: json['defaultAiModel'] as String? ?? '',
      systemTranslationContext: json['systemTranslationContext'] as String? ?? '',
      contextStringsCount: json['contextStringsCount'] as int? ?? 2,
      includeContextStrings: json['includeContextStrings'] as bool? ?? false,
      defaultGitRepositoryPath: json['defaultGitRepositoryPath'] as String,
      autoCommitOnSave: json['autoCommitOnSave'] as bool,
      gitUserName: json['gitUserName'] as String,
      gitUserEmail: json['gitUserEmail'] as String,
      enableGitIntegration: json['enableGitIntegration'] as bool,
      showIdenticalEntries: json['showIdenticalEntries'] as bool? ?? true,
    );
  }

  // To JSON
  Map<String, dynamic> toJson() {
    return {
      'defaultSourceFormat': defaultSourceFormat,
      'defaultTargetFormat': defaultTargetFormat,
      'ignorePatterns': ignorePatterns,
      'ignoreCase': ignoreCase,
      'ignoreWhitespace': ignoreWhitespace,
      'appLanguage': appLanguage,
      'defaultViewOnStartup': defaultViewOnStartup,
      'autoCheckForUpdates': autoCheckForUpdates,
      'appThemeMode': appThemeMode,
      'accentColorValue': accentColorValue,
      'diffAddedColor': diffAddedColor,
      'diffRemovedColor': diffRemovedColor,
      'diffModifiedColor': diffModifiedColor,
      'diffFontSize': diffFontSize,
      'defaultSourceEncoding': defaultSourceEncoding,
      'defaultTargetEncoding': defaultTargetEncoding,
      'autoDetectEncoding': autoDetectEncoding,
      'csvDelimiter': csvDelimiter,
      'handleByteOrderMark': handleByteOrderMark,
      'autoReloadOnChange': autoReloadOnChange,
      'defaultExportDirectory': defaultExportDirectory,
      'aiTranslationService': aiTranslationService,
      'googleTranslateApiKey': googleTranslateApiKey,
      'deeplApiKey': deeplApiKey,
      'enableAiTranslation': enableAiTranslation,
      'translationConfidenceThreshold': translationConfidenceThreshold,
      'geminiApiKey': geminiApiKey,
      'openaiApiKey': openaiApiKey,
      'defaultAiModel': defaultAiModel,
      'systemTranslationContext': systemTranslationContext,
      'contextStringsCount': contextStringsCount,
      'includeContextStrings': includeContextStrings,
      'defaultGitRepositoryPath': defaultGitRepositoryPath,
      'autoCommitOnSave': autoCommitOnSave,
      'gitUserName': gitUserName,
      'gitUserEmail': gitUserEmail,
      'enableGitIntegration': enableGitIntegration,
      'showIdenticalEntries': showIdenticalEntries,
    };
  }

  AppSettings copyWith({
    String? defaultSourceFormat,
    String? defaultTargetFormat,
    List<String>? ignorePatterns,
    bool? ignoreCase,
    bool? ignoreWhitespace,
    String? appLanguage,
    String? defaultViewOnStartup,
    bool? autoCheckForUpdates,
    String? appThemeMode,
    int? accentColorValue,
    int? diffAddedColor,
    int? diffRemovedColor,
    int? diffModifiedColor,
    double? diffFontSize,
    String? defaultSourceEncoding,
    String? defaultTargetEncoding,
    bool? autoDetectEncoding,
    String? csvDelimiter,
    bool? handleByteOrderMark,
    bool? autoReloadOnChange,
    String? defaultExportDirectory,
    String? aiTranslationService,
    String? googleTranslateApiKey,
    String? deeplApiKey,
    bool? enableAiTranslation,
    double? translationConfidenceThreshold,
    String? geminiApiKey,
    String? openaiApiKey,
    String? defaultAiModel,
    String? systemTranslationContext,
    int? contextStringsCount,
    bool? includeContextStrings,
    String? defaultGitRepositoryPath,
    bool? autoCommitOnSave,
    String? gitUserName,
    String? gitUserEmail,
    bool? enableGitIntegration,
    bool? showIdenticalEntries,
  }) {
    return AppSettings(
      defaultSourceFormat: defaultSourceFormat ?? this.defaultSourceFormat,
      defaultTargetFormat: defaultTargetFormat ?? this.defaultTargetFormat,
      ignorePatterns: ignorePatterns ?? this.ignorePatterns,
      ignoreCase: ignoreCase ?? this.ignoreCase,
      ignoreWhitespace: ignoreWhitespace ?? this.ignoreWhitespace,
      appLanguage: appLanguage ?? this.appLanguage,
      defaultViewOnStartup: defaultViewOnStartup ?? this.defaultViewOnStartup,
      autoCheckForUpdates: autoCheckForUpdates ?? this.autoCheckForUpdates,
      appThemeMode: appThemeMode ?? this.appThemeMode,
      accentColorValue: accentColorValue ?? this.accentColorValue,
      diffAddedColor: diffAddedColor ?? this.diffAddedColor,
      diffRemovedColor: diffRemovedColor ?? this.diffRemovedColor,
      diffModifiedColor: diffModifiedColor ?? this.diffModifiedColor,
      diffFontSize: diffFontSize ?? this.diffFontSize,
      defaultSourceEncoding: defaultSourceEncoding ?? this.defaultSourceEncoding,
      defaultTargetEncoding: defaultTargetEncoding ?? this.defaultTargetEncoding,
      autoDetectEncoding: autoDetectEncoding ?? this.autoDetectEncoding,
      csvDelimiter: csvDelimiter ?? this.csvDelimiter,
      handleByteOrderMark: handleByteOrderMark ?? this.handleByteOrderMark,
      autoReloadOnChange: autoReloadOnChange ?? this.autoReloadOnChange,
      defaultExportDirectory: defaultExportDirectory ?? this.defaultExportDirectory,
      aiTranslationService: aiTranslationService ?? this.aiTranslationService,
      googleTranslateApiKey: googleTranslateApiKey ?? this.googleTranslateApiKey,
      deeplApiKey: deeplApiKey ?? this.deeplApiKey,
      enableAiTranslation: enableAiTranslation ?? this.enableAiTranslation,
      translationConfidenceThreshold: translationConfidenceThreshold ?? this.translationConfidenceThreshold,
      geminiApiKey: geminiApiKey ?? this.geminiApiKey,
      openaiApiKey: openaiApiKey ?? this.openaiApiKey,
      defaultAiModel: defaultAiModel ?? this.defaultAiModel,
      systemTranslationContext: systemTranslationContext ?? this.systemTranslationContext,
      contextStringsCount: contextStringsCount ?? this.contextStringsCount,
      includeContextStrings: includeContextStrings ?? this.includeContextStrings,
      defaultGitRepositoryPath: defaultGitRepositoryPath ?? this.defaultGitRepositoryPath,
      autoCommitOnSave: autoCommitOnSave ?? this.autoCommitOnSave,
      gitUserName: gitUserName ?? this.gitUserName,
      gitUserEmail: gitUserEmail ?? this.gitUserEmail,
      enableGitIntegration: enableGitIntegration ?? this.enableGitIntegration,
      showIdenticalEntries: showIdenticalEntries ?? this.showIdenticalEntries,
    );
  }
} 