import 'package:hive/hive.dart';

part 'comparison_history.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 1)
enum ComparisonType {
  @HiveField(0)
  file,
  @HiveField(1)
  directory,
  @HiveField(2)
  git,
}

@HiveType(typeId: 0) // Unique typeId for each HiveObject
class ComparisonSession extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final DateTime timestamp;

  @HiveField(2)
  final String file1Path;

  @HiveField(3)
  final String file2Path;

  @HiveField(4)
  final int stringsAdded;

  @HiveField(5)
  final int stringsRemoved;

  @HiveField(6)
  final int stringsModified;

  @HiveField(7)
  final int stringsIdentical;

  @HiveField(8)
  final int? sourceKeyCount;

  @HiveField(9)
  final int? translatedKeyCount;

  @HiveField(10)
  final int? sourceWordCount;

  @HiveField(11)
  final int? translatedWordCount;

  @HiveField(12)
  final String? projectId;

  @HiveField(13)
  final ComparisonType? type;

  @HiveField(14)
  final String? gitRepoPath;

  @HiveField(15)
  final String? gitBranch1;

  @HiveField(16)
  final String? gitBranch2;

  @HiveField(17)
  final String? gitCommit1;

  @HiveField(18)
  final String? gitCommit2;

  @HiveField(19)
  final int? fileCount;

  ComparisonSession({
    required this.id,
    required this.timestamp,
    required this.file1Path,
    required this.file2Path,
    required this.stringsAdded,
    required this.stringsRemoved,
    required this.stringsModified,
    required this.stringsIdentical,
    this.sourceKeyCount,
    this.translatedKeyCount,
    this.sourceWordCount,
    this.translatedWordCount,
    this.projectId,
    this.type = ComparisonType.file,
    this.gitRepoPath,
    this.gitBranch1,
    this.gitBranch2,
    this.gitCommit1,
    this.gitCommit2,
    this.fileCount,
  });

  // TODO: Add methods for serialization/deserialization if using Hive directly without an adapter
}
