import 'package:hive/hive.dart';

part 'comparison_history.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 0) // Unique typeId for each HiveObject
class ComparisonSession extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final DateTime timestamp;

  @HiveField(2)
  final String file1Path;

  @HiveField(3)
  final String file2Path;

  @HiveField(4)
  final int stringsAdded;

  @HiveField(5)
  final int stringsRemoved;

  @HiveField(6)
  final int stringsModified;

  @HiveField(7)
  final int stringsIdentical;

  ComparisonSession({
    required this.id,
    required this.timestamp,
    required this.file1Path,
    required this.file2Path,
    required this.stringsAdded,
    required this.stringsRemoved,
    required this.stringsModified,
    required this.stringsIdentical,
  });

  // TODO: Add methods for serialization/deserialization if using Hive directly without an adapter
} 
