name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install flet
        pip install colorama
        pip install darkdetect
        pip install gitpython
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git
    
    - name: Lint with flake8
      run: |
        flake8 ./GUI --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./GUI --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest ./GUI/tests/
