name: Test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies and test packages
        run: |
          python -m pip install --upgrade pip
          pip install pytest flet colorama darkdetect gitpython
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest ./tests --maxfail=1 --disable-warnings -v
